name: tag_highlight_text
description: This library will support highlight text by tags with specific styles and tap actions.
version: 1.0.2
homepage: https://github.com/quanbui1998/tag_highlight_text

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
